### ISSUE TITLE
Codeigniter 4

### ISSUE THREAD

**Issue by abelfleitas** [joeauty/RememberMe-CodeIgniter-Spark#7]
You do not plan to migrate the project to codeigniter 4

**Comment by ChibuezeAgwuDennis** [comment]
Contact me I will migrate this to Codeigniter 4

**Comment by joeauty** [comment]
Sorry guys, I wrote this like 9 years ago and have not been maintaining it. I'd be flattered if somebody wanted to fork this and take this over!

**Comment by ChibuezeAgwuDennis** [comment]
Hello I will do it

**Comment by abelfleitas** [comment]
Hello friend, you were able to migrate the repo for codeigniter 4?

**Comment by ChibuezeAgwuDennis** [comment]
> Hello friend, you were able to migrate the repo for codeigniter 4?
<br>
Yes I will soon move it to github
